# Copyright (c) 2021 Thales Group
# This file is distributed under MIT license
version: "3.3"
services:
    application-gateway:
        image: "thalesgroup/application-gateway:1.0.0"
        container_name: application-gateway
        ports:
            - "443:9443"
            - "8443:8443"
        environment:
            ADMIN_CONSOLE_USER: admin
            ADMIN_CONSOLE_PASSWORD: admin
            ENABLE_SSL: "true"
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "50m"
        restart: always 
